global using Blazored.LocalStorage;
global using Microsoft.AspNetCore.Components.Authorization;
global using Shared.Commons;
global using Shared.Models.IdentityModels.Requests.Identity;
global using Shared.Models.IdentityModels.Responses.Identity;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Security.Claims;
global using Web.Infrastructure.ExtensionMethods;
